[tox]
envlist = lint
isolated_build = True
skipsdist = True

[tox:jenkins]
envlist = py{39,313,314}-lint

[testenv]
commands =
	lint: flake8
deps =
	lint: .[lint]

[testenv:lint]
extras = lint
commands = flake8 .
