[tox]
envlist = test, lint
isolated_build = True
skipsdist = True

[tox:jenkins]
envlist = py{39,313,314}-test,py{39,313,314}-lint

[testenv]
commands =
	lint: flake8
	test: python -m unittest
deps =
	lint: .[lint]
	test: .

[testenv:lint]
extras = lint
commands = flake8 .
